### ISSUE TITLE
Review release.yml in light of initial product teams' feedback

### ISSUE THREAD

**Issue by metacosm** [snowdrop/spring-boot-bom#119]
This might need:
- Tweak the message to make the expectations clearer
- Re-shuffle components in a different way
- Add more product definitions associated to starter we own / productize

**Comment by cmoulliard** [comment]
- Description of the jira description was not clear enough, maybe we should shorten it to make it more concile
- Some components should be like RESTeasy re-assigned to EAP instead
- OpenTracing, Narayana, Keycloak should have tickets to figure out the prod version to be used

**Comment by metacosm** [comment]
@zekaguilar @cmoulliard Please review SB-1611 and associated ticket, along with https://github.com/metacosm/spring-boot-bom/blob/updated-release-definition-2.2/release.yml

**Comment by cmoulliard** [comment]
Some remarks after reviewing 2.2 yml file:

- `Vert.X starter name` should become `Vert.x starter`
- Why do you list all these words `Hibernate / Hibernate Validator / Undertow / RESTEasy` at line 25 within the title and not just `Hibernate` ?

**Comment by cmoulliard** [comment]
I agree with your responses Chris :-)

**Comment by geoand** [comment]
LGMT

**Comment by metacosm** [comment]
How about the structure of projects / products and their resulting JIRAs, @cmoulliard @zekaguilar?
