### ISSUE TITLE
Making BOM Simpler

### ISSUE THREAD

**Issue by kameshsampath** [snowdrop/spring-boot-bom#12]
When I was trying to use Spring 1.5.x BOM - I see its too huge with great length of Spring Boot BOM - wondering if we could just import needed spring-<project>-bom in them so that they align with right Spring framework versions

**Comment by cmoulliard** [comment]
@metacosm Can you comment, close, ... please ?

**Comment by metacosm** [comment]
Something to consider for sure, post-1.5.10.

**Comment by metacosm** [comment]
This change is postponed until SB 2.x

**Comment by cmoulliard** [comment]
Can we close it ? @metacosm
