### ISSUE TITLE
Kubernetes/OpenShift Client version conflict

### ISSUE THREAD

**Issue by RadekKoubsky** [snowdrop/spring-boot-bom#2]
In the bom, we explicitly declare version 2.2.14 for both Kubernetes and OpenShift Client. When using this bom in a booster, there is a conflict with Kubernetes/OpenShift client version 1.4.34 within io.openshift:openshift-test-utils which throws .

Workaround si to explicitly declare version in the booster pom:
```
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client</artifactId>
      <version>1.4.34</version>
    </dependency>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>openshift-client</artifactId>
      <version>1.4.34</version>
    </dependency>
```
 In future, we will replace OpenShiftTestAssistant with Arquillian Cube which has its own solution for version conflicts, see [http://arquillian.org/arquillian-cube/#_dealing_with_version_conflicts](http://arquillian.org/arquillian-cube/#_dealing_with_version_conflicts)

**Comment by RadekKoubsky** [comment]
I have found a solution which currently works for both boosters and qe tests. We explicitly declare kubernetes/openshift client v 1.4.34 in the bom and we downgrade spring-cloud-kubernetes-core + spring-cloud-starter-kubernetes-netflix to 0.1.4 (that uses kubernetes client 1.4.34):
```
<version.io.fabric8.kubernetes-client>1.4.34</version.io.fabric8.kubernetes-client>
    <version.io.fabric8.openshift-client>1.4.34</version.io.fabric8.openshift-client>
    <version.io.fabric8.spring-cloud-kubernetes-core>0.1.4</version.io.fabric8.spring-cloud-kubernetes-core>
    <version.io.fabric8.spring-cloud-starter-kubernetes-netflix>0.1.4</version.io.fabric8.spring-cloud-starter-kubernetes-netflix>
```

This targets beta1 as we need compatibility with OpenShiftTestAssistant (openshift-client v1.4.34).

**Comment by cmoulliard** [comment]
> downgrade

I would prefer that we keep the version 2.x for kubernetes/openshift client as spring cloud kubernetes will be released using version 2.x of the client. As the tests look promising to use Arquillian cube (Openshift/Kubernetes), can we replace the openshiftItAssistant in order to use for bossters, qe and integrationTests version 2.x ? @RadekKoubsky

**Comment by RadekKoubsky** [comment]
I am all for version 2.x. However, I have several concerns:

1. Arquillian Cube works for the spring-boot-http booster
But it is not perfect, see [743](https://github.com/arquillian/arquillian-cube/issues/743). I cannot say how it will work with other boosters, there might (will) be issues.
2. Replacing OpenShiftTestAssistant with Arquillian Cube
If we successfully replace it in all spring-boot boosters, other teams will need to replace it as well (if we want to be consistent), and Ladislav might need to update Boosters CI. QE tests use custom deployment for the apps and tests, no work needed here.
3. Time estimates
Speaking about the spring-boot BOM, I am in the context of beta1. Arquillian Cube is target for future. If we want to merge these together, it might take more time to make it work and test.

I think we can implement the BOM with kubernetes-client 1.4.34. When there is time to move to Arquillian Cube and new version of spring-cloud-kubernetes/kubernetes-client, we should be able to switch to the new versions easily by changing versions in the BOM. I suggest this approach as there are too many moving parts for me to embrace.

**Comment by RadekKoubsky** [comment]
I have tested spring-boot-config map with 1.4.34 compatible versions and raised a [PR](https://github.com/snowdrop/spring-boot-configmap-booster/pull/25) to be merged when we release spring-boot-parent.

**Comment by cmoulliard** [comment]
Spring Boot BOM 1.4 is deprecated
