### ISSUE TITLE
Remove Ales Justin as Red Hat Developer

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/spring-boot-bom#34]
The snowdrop BOM but also other projects include Ales Justin as Red Hat Developer. Question 

- Should we remove it from the different projects where it appears ?
- Should we keep it but remove the mention that he is a Red Hat Developer ?

WDYT @geoand @gytis @metacosm @iocanel

**Comment by geoand** [comment]
I would say option 2

**Comment by metacosm** [comment]
Option 2 as well.

**Comment by geoand** [comment]
Closed via  de36c40

**Comment by metacosm** [comment]
That's not the correct commit id ;)

**Comment by geoand** [comment]
Thanks for spotting it @metacosm , fixed now
